"""Print the complete first-time-user workflow.

Run this script before using the repository:

    python scripts/00_show_workflow.py

It prints the same sequence described in ``docs/START_HERE_first_time_user.md``.
"""
from _bootstrap import bootstrap
ROOT = bootstrap(__file__)


if __name__ == "__main__":
    print("TMW/TMCA analysis workflow for first-time users")
    print("=" * 58)
    print()
    print("The code is material-agnostic.  It can be used for AA5083, AA6061,")
    print("AA7075, stainless 304L, Inconel, magnesium alloys, or any other")
    print("material, as long as the manifest describes the condition.")
    print()
    print("INPUTS YOU MUST PREPARE")
    print("1. One controller CSV per weld:")
    print("      time_s, actuator_position_mm, actuator_velocity_mm_s, reaction_force_n")
    print("      optional: temperature_1_c ... temperature_4_c, weld_length_mm")
    print("2. One manifest row per weld:")
    print("      run_id, protocol, control_csv, condition_id, material/process data,")
    print("      weld-start information, crack-length/crack-end measurements")
    print()
    print("RECOMMENDED EXPERIMENTAL AND ANALYSIS SEQUENCE")
    print("1. Perform TMCA tests for fast screening")
    print("   Velocity history: V_high -> V_step -> constant a_dec")
    print("   Fill: data/manifest/my_tmca_manifest.csv")
    print("   Optional manual weld-start picking:")
    print("      python scripts/09_pick_weld_start.py --manifest data/manifest/my_tmca_manifest.csv --run-id RUN_ID --write-manifest")
    print("   Analyze individual tests:")
    print("      python scripts/01_analyze_tmca_screening.py --manifest data/manifest/my_tmca_manifest.csv")
    print("   Check every plot in outputs/01_tmca_run_analysis/run_plots")
    print("   Summarize TMCA:")
    print("      python scripts/02_summarize_tmca_screening.py")
    print()
    print("2. Use TMCA V_NC to plan constant-velocity TMW tests")
    print("   TMCA V_NC is a screening guide, not the final V_C value.")
    print("      python scripts/03_plan_tmw_from_tmca.py")
    print()
    print("3. Perform TMW bracketing tests")
    print("   Velocity history: V_high -> constant V_step")
    print("   Use several V_step values for each condition until no-crack and full-crack")
    print("   endpoints are bracketed.")
    print("   Fill: data/manifest/my_tmw_manifest.csv")
    print("   Optional manual weld-start picking:")
    print("      python scripts/09_pick_weld_start.py --manifest data/manifest/my_tmw_manifest.csv --run-id RUN_ID --write-manifest")
    print("   Analyze individual tests:")
    print("      python scripts/04_analyze_tmw_bracketing.py --manifest data/manifest/my_tmw_manifest.csv")
    print("   Check every plot in outputs/04_tmw_run_analysis/run_plots")
    print()
    print("4. Fit V_C--V_F for each TMW condition")
    print("      python scripts/05_fit_tmw_conditions.py")
    print("   This creates one L* vs. V_step plot per condition.")
    print()
    print("5. Compare all conditions")
    print("      python scripts/06_compare_tmw_conditions.py")
    print("   This creates the final cross-condition V_C--V_F comparison plot.")
    print()
    print("6. Reproduce the manuscript summary figures only")
    print("      python scripts/reproduce_all.py")
    print()
    print("WHERE TO CHANGE OPTIONS")
    print("- Show/hide temperature: manifest column show_temperature or config/default_analysis_config.json")
    print("- Single-run plot appearance: src/tmw_tmca_analysis/plots.py")
    print("- Run-level metric definitions: src/tmw_tmca_analysis/run_analysis.py")
    print("- TMW transition fitting: src/tmw_tmca_analysis/metrics.py")
    print("- Manifest columns: docs/run_manifest_specification.md")
    print()
    print("Read first: docs/START_HERE_first_time_user.md")
